version: "3.2"
services:

  backend:
    restart: always
    container_name: backend
    env_file:
      - ./rsspy-backend/.env
    volumes:
      - "C:/Users/Chris/rsspy-db:/app/api/database"
    ## TODO: this isn't recommended in prod, this should be served by a proxy like nginx
    command : bash -c "/etc/init.d/cron start;
                      source ./rsspy-backend/.env;
                      python3 manage.py makemigrations ;
                      python3 manage.py migrate ;
                      python manage.py crontab add;
                      python3 manage.py runscript coin_updater ;
                      python3 manage.py runserver 0.0.0.0:8000" 
    # ports:
    #   - 8000:8000  expose this if you want access to backend
    # If you want access to django admin run 'docker exec backend python3 /app/api/manage.py createsuperuser --username $USERNAME --password $PASSWORD'
    build:
      context: ./rsspy-backend/
      dockerfile: Dockerfile

  frontend:
    restart: always
    container_name: frontend
    command: sh -c 'gatsby serve -H frontend -p 3500'
    build:
      context: ./rsspy-frontend/
      dockerfile: Dockerfile
    depends_on:
      - backend

  rsspy:
    restart: always
    container_name: proxy
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
