# Generated by Django 4.0.1 on 2022-01-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('coinName', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=128)),
                ('data', models.JSONField()),
                ('currentBuzzScore', models.IntegerField(default=0)),
                ('previousBuzzScore', models.IntegerField(default=0)),
            ],
        ),
    ]
